# Generated by Django 5.1.5 on 2025-01-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_counties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='dis',
            field=models.IntegerField(null=True),
        ),
    ]
