# Generated by Django 5.1.5 on 2025-01-24 20:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_alter_counties_dis'),
    ]

    operations = [
        migrations.CreateModel(
            name='berlin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
                ('ew2022', models.BigIntegerField()),
                ('area', models.FloatField()),
                ('pop_density', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
