# Generated by Django 5.1.5 on 2025-01-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_berlin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidences',
            options={},
        ),
    ]
